# Generated by Django 4.2.3 on 2023-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_cart_product_order_customer_cartproduct_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='None', upload_to='product'),
        ),
    ]
